-- Job applications and their uploaded resume (see model/Application.java)
CREATE TABLE application (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(255),
    document     BYTEA,
    is_submitted BOOLEAN      NOT NULL,
    status       VARCHAR(255),
    CONSTRAINT application_pkey PRIMARY KEY (id)
);
