-- Let the database assign ids to new users, starting after any existing rows.
-- (H2 needs different syntax for this, see db/migration/h2.)
ALTER TABLE person_user ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE employer_user ALTER COLUMN employer_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('person_user', 'person_id'),
              COALESCE((SELECT MAX(person_id) FROM person_user), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('employer_user', 'employer_id'),
              COALESCE((SELECT MAX(employer_id) FROM employer_user), 0) + 1, false);

