-- H2 version of db/migration/postgresql/V3 for the tests. The tables are empty
-- here, so the ids can start at 1.
ALTER TABLE person_user ALTER COLUMN person_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE employer_user ALTER COLUMN employer_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
